### ISSUE TITLE
Pinning revisions or cabal file hash

### ISSUE THREAD

**Issue by nmattia** [FormationAI/hazel#51]
Looking at `Stackage.hs`

https://github.com/FormationAI/hazel/blob/925293994f88799ba550fd5cf3995104d1f2972c/Stackage.hs#L54-L56

it appears that the packages are downloaded using the `https://hackage.haskell.org/package/<package-name>-<package-version>.tar.gz` URL, and then the `sha256` is computed and inserted into `packages.bzl`. This `sha256` is then used 

https://github.com/FormationAI/hazel/blob/925293994f88799ba550fd5cf3995104d1f2972c/hazel.bzl#L24-L28

in Bazel's [`download_and_extract`](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#download_and_extract).

AFAICT this can lead to the following situation:

1. `Stackage.hs` is run to generate `packages.bzl` which includes package `pkg` at version `ver`
2. A new revision of `pkg` is introduced, still at version `ver`
3. `bazel build` is called with the `packages.bzl` containing the `sha256` for the old tarball, which will try to download the tarball of the latest revision, which will fail the build (the `sha256`s do not match anymore)

There may be solutions to this by using the resolver's `cabal-file-info` fields:

``` yaml
packages:
  drawille:
    users: []
    constraints:
      ...
    version: '0.1.2.0'
    cabal-file-info:
      size: 2409
      hashes:
        MD5: 1518765abeeb698adbc558de46d45222
        Skein512_512: a99229bbb75b0395649e6e0a571c1fa69617803486377f100b6724ad65693c80be6b81d27b47c4ca64065ba6adfd24b4738f04bd77ffc9e20584efb7863fa2bf
        SHA1: d44b178055fb373978f9052d513e429b929a6dd7
        SHA512: 345426ecaf3fb3db4093cd17a3bf87f44424cd16422d946db8896ec09681fe95ad8dee061744f05002bae09182c133e00d91702f4bcc8da462b672d79f8ded72
        SHA256: 41a1627890649690d76261040c67779fa2e6fa2eb0ff912ee24891ea21b7b2f7
        GitSHA1: dfe6d875faa4af01d4cba1e215e0da5e0885db7c
```
although I can never remember whether there's an URL for downloading a package from Hackage by specifying either the revision or the cabal file's hash.
